name: Test
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Install dependencies from composer.json"
        uses: "php-actions/composer@v6"
        with:
          php_extensions: yaml gettext
      #- name: "Static Code Analysis"
      #  run: "composer analyse"
      - name: "PHPUnit"
        run: "composer test"
